baseurl = "http://www.roycewells.io"
languageCode = "en-us"
title = "royce wells"
PluralizeListTitles = false
theme = "hyde-royce"

[params]

	tagline = "Creating digital products."
	description = "digital products"

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about"
[[menu.main]]
    name = "posts"
    url = "/posts"
