baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "&Wells"

[params]

	tagline = "An old-fashioned agency for a digital world."
	description = "An old-fashioned agency for a digital world."