baseurl = "http://roycewells.io.s3-website-us-west-2.amazonaws.com/"
languageCode = "en-us"
title = "Royce Wells"
PluralizeListTitles = false
theme = "and-wells"

[params]

	tagline = "Creating digital products."
	description = "An old-fashioned agency for a digital world."