baseurl = "http://www.roycewells.io"
languageCode = "en-us"
title = "royce wells"
PluralizeListTitles = false
theme = "hyde-royce"

[params]

	tagline = "digital product"
	description = "digital product"
    disqusShortname = "roycewells-io"

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 3
[[menu.main]]
    name = "writing"
    url = "/writing"
    weight = 2

[[menu.social]]
    name = "twitter"
    identifier = "twitter"
    url = "https://twitter.com/thatroyce"
    weight = 1
[[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/roycewells/"
    weight = 2
[[menu.social]]
    name = "github"
    url = "https://github.com/comraderoyce"
    weight = 3
[[menu.social]]
    name = "envelope"
    url = "mailto:wells.royce@gmail.com"
    weight = 4
