baseurl = "https://roycewells.io"
languageCode = "en-us"
title = "royce wells"
PluralizeListTitles = false
theme = "hugo-tufte-royce"
rssLimit = 23
enableGitInfo = true
footnoteReturnLinkContents = "↩"
pygmentsCodeFences = true
PygmentsStyle = "pygments"
enableEmoji = true 

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "RSS"]  

[params]

  tagline = "Building some things and tearing down others."
  description = "This is my personal website where I write about designing and building digital products."
  disqusShortname = "roycewells-io"
  # author = "Royce Wells"
  images = ["https://source.unsplash.com/1600x900/?nature,water"]
  blogRepo = "https://github.com/comraderoyce/and-wells/"

  # for tufte theme
  meta = true
  showPoweredBy = false
  copyrightHolder = "Royce Wells"


[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "writing"
    url = "/writing"
    weight = 2
[[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 3

[[menu.social]]
    name = "twitter"
    identifier = "twitter"
    url = "https://twitter.com/thatroyce"
    weight = 1
[[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/roycewells/"
    weight = 2
[[menu.social]]
    name = "github"
    url = "https://github.com/comraderoyce"
    weight = 3
[[menu.social]]
    name = "envelope"
    url = "mailto:wells.royce@gmail.com"
    weight = 4
[[menu.social]]
    name = "rss"
    url = "/index.xml"
    weight = 5

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  # pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -120 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "About"
  # pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "about"
  url = "/about"  
[[menu.nav]]
  name = "Writing"
  # pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "Writing"
  url = "/writing"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/comraderoyce"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com/thatRoyce"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-envelope fa-2x'></i> "
  weight = -80 
  identifier = "email"
  url = "mailto:wells.royce@gmail.com"
