baseurl = "http://www.roycewells.io"
languageCode = "en-us"
title = "royce wells"
PluralizeListTitles = false
theme = "hyde-royce"

[params]

	tagline = "Creating digital products."
	description = "digital products"

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 3
[[menu.main]]
    name = "writing"
    url = "/writing"
    weight = 2

