baseurl = "http://www.roycewells.io"
languageCode = "en-us"
title = "royce wells"
PluralizeListTitles = false
theme = "hyde-royce"
rssLimit = 23
enableGitInfo = true
footnoteReturnLinkContents = "↩"
pygmentsCodeFences = true
PygmentsStyle = ""

[taxonomies]
  tag = "tags"
  category = "categories"

[params]

  tagline = "Building some things and tearing down others."
  description = "This is my personal website where I write about designing and building digital products."
  disqusShortname = "roycewells-io"
  author = "Royce Wells"
  images = ["https://source.unsplash.com/1600x900/?nature,water"]
  blogRepo = "https://github.com/comraderoyce/and-wells/"

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "writing"
    url = "/writing"
    weight = 2
[[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 3

[[menu.social]]
    name = "twitter"
    identifier = "twitter"
    url = "https://twitter.com/thatroyce"
    weight = 1
[[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/roycewells/"
    weight = 2
[[menu.social]]
    name = "github"
    url = "https://github.com/comraderoyce"
    weight = 3
[[menu.social]]
    name = "envelope"
    url = "mailto:wells.royce@gmail.com"
    weight = 4
[[menu.social]]
    name = "rss"
    url = "/index.xml"
    weight = 5
