baseurl = "http://www.roycewells.io"
languageCode = "en-us"
title = "Royce Wells"
PluralizeListTitles = false
theme = "royce"

[params]

	tagline = "Creating digital products."
	description = "An old-fashioned agency for a digital world."