baseurl = "http://www.roycewells.io"
languageCode = "en-us"
title = "royce wells"
PluralizeListTitles = false
theme = "hyde-royce"
rssLimit = 23

[params]

	tagline = "Building some things and tearing down others."
	description = "This is my personal website where I write about designing and building digital products. -Royce"
  disqusShortname = "roycewells-io"
  author = "Royce Wells"

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 3
[[menu.main]]
    name = "writing"
    url = "/writing"
    weight = 2

[[menu.social]]
    name = "twitter"
    identifier = "twitter"
    url = "https://twitter.com/thatroyce"
    weight = 1
[[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/roycewells/"
    weight = 2
[[menu.social]]
    name = "github"
    url = "https://github.com/comraderoyce"
    weight = 3
[[menu.social]]
    name = "envelope"
    url = "mailto:wells.royce@gmail.com"
    weight = 4
